import type { Lang } from "../i18n/types";

export interface ModelPageContent {
  slug: string;
  title: string;
  eyebrow: string;
  lead: string;
  sections: { heading: string; html: string }[];
  footerLink: { href: string; label: string };
}

const pages: Record<Lang, ModelPageContent[]> = {
  en: [
    {
      slug: "yolov8n-detection",
      title: "YOLOv8n — Object Detection",
      eyebrow: "Detection model",
      lead: "Nano model pre-trained on the COCO dataset (80 classes). Used for image and video detection.",
      sections: [
        {
          heading: "Specifications",
          html: `<ul>
            <li><strong>File:</strong> yolov8n.pt (~6 MB)</li>
            <li><strong>Architecture:</strong> YOLOv8 nano — optimized for speed</li>
            <li><strong>Training dataset:</strong> COCO (80 classes: person, car, dog…)</li>
            <li><strong>Output:</strong> bounding boxes + confidence score + class label</li>
            <li><strong>Threshold used:</strong> confidence ≥ 0.5</li>
          </ul>`,
        },
        {
          heading: "Image results",
          html: `<p>On <code>input/test_image.jpg</code> (parking lot scene):</p>
          <ul>
            <li>4 cars detected (class <em>car</em>)</li>
            <li>Maximum confidence: 89.5%</li>
            <li>Minimum confidence: 73.9%</li>
          </ul>`,
        },
        {
          heading: "Video results",
          html: `<p>On <code>input/test_video_1.mp4</code> → <code>output/test_video_2.mp4</code>:</p>
          <ul>
            <li>721 frames processed at 1920×1080 @ 30 fps (~24 seconds)</li>
            <li>Full annotated video generated by <code>detect_video.py</code></li>
            <li>Preview available on the <a href="#results">results page</a></li>
          </ul>
          <div class="info-box"><p><strong>Related scripts:</strong> detect_image.py, detect_video.py, detect_tracking.py (base detection)</p></div>`,
        },
        {
          heading: "Speed vs. accuracy trade-off",
          html: `<p>YOLOv8n is the fastest model in the YOLOv8 family. Ideal for prototyping and CPU inference. For higher accuracy, yolov8s/m/l variants can be tested by changing <code>MODEL</code> in config.py.</p>`,
        },
      ],
      footerLink: { href: "#results", label: "View results" },
    },
    {
      slug: "yolov8n-segmentation",
      title: "YOLOv8n-seg — Instance Segmentation",
      eyebrow: "Segmentation model",
      lead: "Beyond bounding boxes, this model produces precise masks that follow the actual contour of each object.",
      sections: [
        {
          heading: "Difference from standard detection",
          html: `<ul>
            <li><strong>Detection:</strong> enclosing rectangle (bbox)</li>
            <li><strong>Segmentation:</strong> binary mask + polygon contour (masks.xy)</li>
          </ul>`,
        },
        {
          heading: "Specifications",
          html: `<ul>
            <li><strong>File:</strong> yolov8n-seg.pt (~6.7 MB)</li>
            <li><strong>Outputs:</strong> bbox + masks (N, H, W) + polygons</li>
            <li><strong>Script:</strong> detect_segmentation.py</li>
          </ul>`,
        },
        {
          heading: "Test results",
          html: `<p>On the same parking lot image:</p>
          <ul>
            <li>4 cars segmented</li>
            <li>Contours from 33 to 234 points depending on shape complexity</li>
            <li>Confidence: 68% to 90%</li>
          </ul>
          <div class="info-box"><p><strong>Use cases:</strong> occupied area measurement, precise cropping, shape analysis — where a simple bbox is not enough.</p></div>`,
        },
      ],
      footerLink: { href: "#results", label: "View results" },
    },
    {
      slug: "tracking-bytetrack",
      title: "ByteTrack — Object Tracking",
      eyebrow: "Multi-object tracking",
      lead: "Combines YOLOv8 detection with a tracking algorithm to assign a unique ID to each object across frames.",
      sections: [
        {
          heading: "How it works",
          html: `<ul>
            <li><code>model.predict()</code> → detects without identity (each frame is independent)</li>
            <li><code>model.track(persist=True)</code> → detects + maintains ID across frames</li>
          </ul>`,
        },
        {
          heading: "Configuration used",
          html: `<ul>
            <li><strong>Tracker:</strong> bytetrack.yaml (built into Ultralytics)</li>
            <li><strong>persist:</strong> True (state preserved between calls)</li>
            <li><strong>Detection model:</strong> yolov8n.pt</li>
            <li><strong>Script:</strong> detect_tracking.py</li>
          </ul>`,
        },
        {
          heading: "Exports",
          html: `<ul>
            <li>Annotated video with IDs: <code>output/tracking_video.mp4</code></li>
            <li>Trajectory CSV: frame, track_id, class, bbox</li>
          </ul>
          <div class="info-box"><p><strong>Use cases:</strong> counting <em>distinct</em> people in a video, trajectory analysis, intelligent video surveillance.</p></div>`,
        },
      ],
      footerLink: { href: "#results", label: "View results" },
    },
    {
      slug: "custom-training",
      title: "Training on Custom Classes",
      eyebrow: "Fine-tuning",
      lead: "Pipeline ready to train YOLOv8 on an annotated dataset via transfer learning from COCO weights.",
      sections: [
        {
          heading: "Training pipeline",
          html: `<ol>
            <li>Collect 50–200 images of the target object</li>
            <li>Annotate (Roboflow, LabelImg) in YOLO format</li>
            <li>Organize into <code>dataset/images</code> and <code>dataset/labels</code></li>
            <li>Configure <code>dataset/dataset.yaml</code> (nc + names)</li>
            <li>Run <code>python train.py</code></li>
          </ol>`,
        },
        {
          heading: "Configured parameters",
          html: `<ul>
            <li><strong>Base model:</strong> yolov8n.pt</li>
            <li><strong>Epochs:</strong> 50</li>
            <li><strong>Image size:</strong> 640 px</li>
            <li><strong>Batch:</strong> 16</li>
            <li><strong>Output:</strong> runs/train/yolo_custom/weights/best.pt</li>
          </ul>`,
        },
        {
          heading: "Current status",
          html: `<p>The pipeline is <strong>fully implemented</strong> (train.py script + dataset structure). The custom dataset is not yet populated — this section will be updated with screenshots, metrics (mAP50), and detection examples once a custom model is trained.</p>
          <div class="info-box"><p><strong>Next portfolio step:</strong> after training, add class names, image count, mAP50, and before/after screenshots for the custom model here.</p></div>`,
        },
        {
          heading: "Example use cases",
          html: `<ul>
            <li>Hard hat / safety vest detection on construction sites</li>
            <li>Specific product recognition</li>
            <li>Quality defect detection</li>
            <li>Custom face recognition</li>
          </ul>`,
        },
      ],
      footerLink: {
        href: "https://github.com/voksir/image-detection",
        label: "Source code",
      },
    },
  ],
  fr: [
    {
      slug: "yolov8n-detection",
      title: "YOLOv8n — Détection d'objets",
      eyebrow: "Modèle de détection",
      lead: "Modèle nano pré-entraîné sur le dataset COCO (80 classes). Utilisé pour la détection sur image et vidéo.",
      sections: [
        {
          heading: "Caractéristiques",
          html: `<ul>
            <li><strong>Fichier :</strong> yolov8n.pt (~6 MB)</li>
            <li><strong>Architecture :</strong> YOLOv8 nano — optimisé vitesse</li>
            <li><strong>Dataset d'entraînement :</strong> COCO (80 classes : person, car, dog…)</li>
            <li><strong>Sortie :</strong> bounding boxes + score de confiance + classe</li>
            <li><strong>Seuil utilisé :</strong> confidence ≥ 0.5</li>
          </ul>`,
        },
        {
          heading: "Résultat sur image",
          html: `<p>Sur <code>input/test_image.jpg</code> (scène de parking) :</p>
          <ul>
            <li>4 voitures détectées (classe <em>car</em>)</li>
            <li>Confiance maximale : 89,5 %</li>
            <li>Confiance minimale : 73,9 %</li>
          </ul>`,
        },
        {
          heading: "Résultat sur vidéo",
          html: `<p>Sur <code>input/test_video_1.mp4</code> → <code>output/test_video_2.mp4</code> :</p>
          <ul>
            <li>721 frames traitées en 1920×1080 @ 30 fps (~24 secondes)</li>
            <li>Vidéo annotée complète générée par <code>detect_video.py</code></li>
            <li>Aperçu disponible sur la <a href="#resultats">page résultats</a></li>
          </ul>
          <div class="info-box"><p><strong>Scripts associés :</strong> detect_image.py, detect_video.py, detect_tracking.py (base detection)</p></div>`,
        },
        {
          heading: "Trade-off vitesse / précision",
          html: `<p>YOLOv8n est le modèle le plus rapide de la famille. Idéal pour prototypage et CPU. Pour plus de précision, les variantes yolov8s/m/l peuvent être testées en changeant <code>MODEL</code> dans config.py.</p>`,
        },
      ],
      footerLink: { href: "#resultats", label: "Voir les résultats" },
    },
    {
      slug: "yolov8n-segmentation",
      title: "YOLOv8n-seg — Segmentation d'instance",
      eyebrow: "Modèle de segmentation",
      lead: "Au-delà des bounding boxes, ce modèle produit des masques précis suivant le contour réel de chaque objet.",
      sections: [
        {
          heading: "Différence avec la détection standard",
          html: `<ul>
            <li><strong>Détection :</strong> rectangle englobant (bbox)</li>
            <li><strong>Segmentation :</strong> masque binaire + contour polygonal (masks.xy)</li>
          </ul>`,
        },
        {
          heading: "Caractéristiques",
          html: `<ul>
            <li><strong>Fichier :</strong> yolov8n-seg.pt (~6,7 MB)</li>
            <li><strong>Sorties :</strong> bbox + masks (N, H, W) + polygones</li>
            <li><strong>Script :</strong> detect_segmentation.py</li>
          </ul>`,
        },
        {
          heading: "Résultats de test",
          html: `<p>Sur la même image de parking :</p>
          <ul>
            <li>4 voitures segmentées</li>
            <li>Contours de 33 à 234 points selon la complexité</li>
            <li>Confiance : 68 % à 90 %</li>
          </ul>
          <div class="info-box"><p><strong>Cas d'usage :</strong> mesure de surface occupée, recadrage précis, analyse de forme — là où une simple bbox ne suffit pas.</p></div>`,
        },
      ],
      footerLink: { href: "#resultats", label: "Voir les résultats" },
    },
    {
      slug: "tracking-bytetrack",
      title: "ByteTrack — Suivi d'objets",
      eyebrow: "Tracking multi-objets",
      lead: "Combine la détection YOLOv8 avec un algorithme de tracking pour attribuer un ID unique à chaque objet entre les frames.",
      sections: [
        {
          heading: "Fonctionnement",
          html: `<ul>
            <li><code>model.predict()</code> → détecte sans identité (chaque frame est indépendante)</li>
            <li><code>model.track(persist=True)</code> → détecte + maintient l'ID entre les frames</li>
          </ul>`,
        },
        {
          heading: "Configuration utilisée",
          html: `<ul>
            <li><strong>Tracker :</strong> bytetrack.yaml (intégré Ultralytics)</li>
            <li><strong>persist :</strong> True (état conservé entre appels)</li>
            <li><strong>Modèle de détection :</strong> yolov8n.pt</li>
            <li><strong>Script :</strong> detect_tracking.py</li>
          </ul>`,
        },
        {
          heading: "Exports",
          html: `<ul>
            <li>Vidéo annotée avec IDs : <code>output/tracking_video.mp4</code></li>
            <li>CSV trajectoires : frame, track_id, class, bbox</li>
          </ul>
          <div class="info-box"><p><strong>Cas d'usage :</strong> compter des personnes <em>distinctes</em> dans une vidéo, analyse de trajectoires, vidéosurveillance intelligente.</p></div>`,
        },
      ],
      footerLink: { href: "#resultats", label: "Voir les résultats" },
    },
    {
      slug: "custom-training",
      title: "Entraînement sur classes personnalisées",
      eyebrow: "Fine-tuning",
      lead: "Pipeline prêt pour entraîner YOLOv8 sur un dataset annoté via transfer learning depuis les poids COCO.",
      sections: [
        {
          heading: "Pipeline d'entraînement",
          html: `<ol>
            <li>Collecter 50–200 images de l'objet cible</li>
            <li>Annoter (Roboflow, LabelImg) au format YOLO</li>
            <li>Organiser dans <code>dataset/images</code> et <code>dataset/labels</code></li>
            <li>Configurer <code>dataset/dataset.yaml</code> (nc + names)</li>
            <li>Lancer <code>python train.py</code></li>
          </ol>`,
        },
        {
          heading: "Paramètres configurés",
          html: `<ul>
            <li><strong>Modèle de base :</strong> yolov8n.pt</li>
            <li><strong>Epochs :</strong> 50</li>
            <li><strong>Taille image :</strong> 640 px</li>
            <li><strong>Batch :</strong> 16</li>
            <li><strong>Sortie :</strong> runs/train/yolo_custom/weights/best.pt</li>
          </ul>`,
        },
        {
          heading: "Statut actuel",
          html: `<p>Le pipeline est <strong>entièrement implémenté</strong> (script train.py + structure dataset). Le dataset custom n'est pas encore peuplé — cette section sera mise à jour avec captures, métriques (mAP50) et exemples de détection une fois un modèle entraîné.</p>
          <div class="info-box"><p><strong>Prochaine étape portfolio :</strong> après entraînement, ajouter noms de classes, nombre d'images, mAP50 et captures avant/après ici.</p></div>`,
        },
        {
          heading: "Exemples de cas d'usage",
          html: `<ul>
            <li>Détection casque / gilet de sécurité sur chantier</li>
            <li>Reconnaissance de produit spécifique</li>
            <li>Détection de défauts qualité</li>
            <li>Reconnaissance faciale personnalisée</li>
          </ul>`,
        },
      ],
      footerLink: {
        href: "https://github.com/voksir/image-detection",
        label: "Code source",
      },
    },
  ],
};

export function getModelPages(lang: Lang): ModelPageContent[] {
  return pages[lang];
}

export function getModelPage(lang: Lang, slug: string): ModelPageContent | undefined {
  return pages[lang].find((p) => p.slug === slug);
}

export function getAllModelSlugs(): string[] {
  return pages.en.map((p) => p.slug);
}
